stages:
  preprocess:
    cmd: python3 preprocess_dataset.py
    deps:
    - preprocess_dataset.py
    - raw_dataset/weather.csv
    - utils_and_constants.py
    outs:
    - processed_dataset/weather.csv
  train:
    cmd: python3 train.py
    deps:
    - metrics_and_plots.py
    - model.py
    - processed_dataset/weather.csv
    - train.py
    - utils_and_constants.py
    metrics:
      # Specify the metrics file as target
      - metrics.json:
          cache: false
    plots:
      # Set the target to the file containing predictions data
      - predictions.csv: # Name of file containing predictions
          # Write the plot template
          template: confusion_normalized # Style of plot
          x: predicted_label # X-axis column name is csv file
          y: true_label # Y-axis column name in csv file
          x_label: 'Predicted label' 
          y_label: 'True label'
          title: Confusion matrix
          # Set the cache parameter to store
          # plot data in git repository
          cache: false # Save in Git